"""Initial migration

Revision ID: c12c9e2e26e1
Revises: 
Create Date: 2026-06-09 15:59:16.467089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12c9e2e26e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narrator_voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_voice_id', sa.String(length=255), nullable=False),
    sa.Column('persona', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('default_tts_settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('provider_voice_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_narrator_voices_id'), 'narrator_voices', ['id'], unique=False)
    op.create_table('meditation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_reference', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('narrator_voice_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('emotion', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('body_tension_areas', sa.JSON(), nullable=False),
    sa.Column('nature_sound', sa.String(length=255), nullable=False),
    sa.Column('landscape', sa.String(length=255), nullable=False),
    sa.Column('questionnaire_answers', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['narrator_voice_id'], ['narrator_voices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meditation_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('script_json', sa.JSON(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('storage_metadata', sa.JSON(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['meditation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meditation_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('end_time_seconds', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['meditation_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playback_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('user_reference', sa.String(length=255), nullable=False),
    sa.Column('current_position_seconds', sa.Integer(), nullable=False),
    sa.Column('current_step_type', sa.String(length=64), nullable=False),
    sa.Column('completion_percent', sa.Float(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['meditation_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playback_tracking')
    op.drop_table('meditation_steps')
    op.drop_table('meditation_artifacts')
    op.drop_table('meditation_sessions')
    op.drop_index(op.f('ix_narrator_voices_id'), table_name='narrator_voices')
    op.drop_table('narrator_voices')
    # ### end Alembic commands ###
