# Generated by Django 6.0.4 on 2026-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charectervoice',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/characters'),
        ),
    ]
