# Generated by Django 6.0.4 on 2026-05-19 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_charectervoice_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('experience_question_answer', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(choices=[('relaxation', 'Entspannung'), ('self_love', 'Selbstliebe'), ('focus_clarity', 'Fokus & Klarheit'), ('gratitude', 'Dankbarkeit'), ('trust', 'Vertrauen'), ('energy', 'Energie'), ('transformation', 'Transformation'), ('inner_peace', 'Innerer Frieden')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.backgroundimage')),
                ('charecter_voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.charectervoice')),
                ('nature_sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.naturesounds')),
            ],
        ),
        migrations.CreateModel(
            name='MeditationSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('greeting', 'Begrüßung'), ('personal', 'Persönlich'), ('introduction', 'Einführung'), ('suggestion', 'Vorschlag'), ('confirmation', 'Bestätigung'), ('visualization', 'Visualisierung'), ('conclusion', 'Abschluss')], max_length=50)),
                ('content', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/audio')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.meditation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
