# Generated by Django 6.0.4 on 2026-05-19 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_meditation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='user',
            field=models.ForeignKey(default='60e48f31-e159-4117-813a-3a246095f59e', on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
