# Generated by Django 6.0.4 on 2026-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_meditation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='charectervoice',
            name='elevenlabs_voice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
