# Generated by Django 6.0.4 on 2026-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_charectervoice_elevenlabs_voice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/audio')),
                ('category', models.CharField(blank=True, choices=[('relaxation', 'Entspannung'), ('self_love', 'Selbstliebe'), ('focus_clarity', 'Fokus & Klarheit'), ('gratitude', 'Dankbarkeit'), ('trust', 'Vertrauen'), ('energy', 'Energie'), ('transformation', 'Transformation'), ('inner_peace', 'Innerer Frieden')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
