# Generated by Django 6.0.4 on 2026-06-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('relaxation', 'Entspannung'), ('self_love', 'Selbstliebe'), ('focus_clarity', 'Fokus & Klarheit'), ('gratitude', 'Dankbarkeit'), ('trust', 'Vertrauen'), ('energy', 'Energie'), ('transformation', 'Transformation'), ('inner_peace', 'Innerer Frieden')], db_index=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meditationsteps',
            name='meditation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.meditation'),
        ),
        migrations.AddField(
            model_name='meditationsteps',
            name='meditation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.meditationtemplate'),
        ),
    ]
