# Generated by Django 6.0.4 on 2026-07-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_meditationtemplate_alter_meditationsteps_meditation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationtemplate',
            name='charecter_voice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='main.charectervoice'),
        ),
    ]
