# Generated by Django 6.0.4 on 2026-07-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_meditationtemplate_charecter_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditationsteps',
            name='step_type',
            field=models.CharField(choices=[('greeting', 'Begrüßung'), ('personal', 'Persönlich'), ('introduction', 'Einführung'), ('transition', 'Übergang'), ('suggestion', 'Vorschlag'), ('confirmation', 'Bestätigung'), ('visualization', 'Visualisierung'), ('conclusion', 'Abschluss')], max_length=50),
        ),
        migrations.AlterField(
            model_name='meditationtemplate',
            name='charecter_voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='main.charectervoice'),
        ),
    ]
