# Generated by Django 6.0.4 on 2026-07-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_meditationsteps_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditationsteps',
            name='step_type',
            field=models.CharField(choices=[('greeting', 'Begrüßung'), ('personal', 'Persönlich'), ('introduction', 'Einführung'), ('transition', 'Übergang'), ('suggestion', 'Vorschlag'), ('confirmation', 'Bestätigung'), ('visualization', 'Visualisierung'), ('conclusion', 'Abschluss')], max_length=50),
        ),
    ]
