# Generated by Django 6.0.4 on 2026-06-29 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability', models.FloatField(default=0.4, help_text='Stability value must be between 0.0 and 1.0 (Default: 0.40)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('similarity_boost', models.FloatField(default=0.6, help_text='Similarity boost must be between 0.0 and 1.0 (Default: 0.60)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('style', models.FloatField(default=0.45, help_text='Style must be between 0.0 and 1.0 (Default: 0.45)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('use_speaker_boost', models.BooleanField(default=True, help_text='Toggle speaker boost (Default: True)')),
            ],
            options={
                'verbose_name': 'TTS Settings',
                'verbose_name_plural': 'TTS Settings',
            },
        ),
    ]
