# Generated by Django 6.0.4 on 2026-07-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt_template', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meditation Prompt',
                'verbose_name_plural': 'Meditation Prompts',
            },
        ),
    ]
