# Generated by Django 6.0.4 on 2026-07-29 03:51

from django.db import migrations


def populate_default_prompt(apps, schema_editor):
    from apps.ai_service.meditation import DEFAULT_PROMPT_TEMPLATE
    MeditationPrompt = apps.get_model('ai_service', 'MeditationPrompt')
    MeditationPrompt.objects.create(
        name="Default Prompt",
        prompt_template=DEFAULT_PROMPT_TEMPLATE,
        is_active=True
    )

def remove_default_prompt(apps, schema_editor):
    MeditationPrompt = apps.get_model('ai_service', 'MeditationPrompt')
    MeditationPrompt.objects.filter(name="Default Prompt").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_meditationprompt'),
    ]

    operations = [
        migrations.RunPython(populate_default_prompt, reverse_code=remove_default_prompt),
    ]
