# Generated by Django 6.0.4 on 2026-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0003_auto_20260729_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationprompt',
            name='category',
            field=models.CharField(choices=[('relaxation', 'Entspannung'), ('self_love', 'Selbstliebe'), ('focus_clarity', 'Fokus & Klarheit'), ('gratitude', 'Dankbarkeit'), ('trust', 'Vertrauen'), ('energy', 'Energie'), ('transformation', 'Transformation'), ('inner_peace', 'Innerer Frieden')], default='relaxation', max_length=50),
        ),
    ]
